spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/mybatis-test
    username: sa
    password:
  sql:
    init:
      mode: always
      platform: h2
